system:
    debug: 0
    error_reporting: 0
    timezone: 'UTC'
    secret: e2946a5b829240a67bb257b3b9e33e05
session:
    handler: native
    expire_time: 15
routing:
    debug: 0
cache:
    enabled: 0
    storage: file
    handler: serialize
    dir: cache
    time: 15
language:
    debug: 0
    locale: en-GB
    default: en-GB
    format: ini
    path: resources/languages
